[package]
name = "libspook"
version = "0.1.0"
edition = "2021"
description = """
libspook injects libraries into a process by taking advantage of a very
specific form of phantom DLL hijacking.
"""

[lib]
crate-type = ["cdylib"]

[features]
debug = []
