[package]
name = "libspook"
version = "0.1.0"
edition = "2021"
description = """
libspook loads other libraries by taking the place of a phantom library.

Refer to this blog post for more information:
https://shonk.sh/posts/chasing-ghosts/"""

[lib]
crate-type = ["cdylib"]

[features]
debug = []
